XraySocialClub/Areas/Administration/Controllers/AnnouncementController.cs
using Microsoft.AspNetCore.Mvc;
using X.PagedList.Extensions;
using XraySocialClub.Areas.Administration.Models.Announcement;
using XraySocialClub.Data.Core;
using XraySocialClub.Services;
using System.Security.Claims;

namespace XraySocialClub.Areas.Administration.Controllers
{
    public class AnnouncementController : AdministrationController
    {
        private readonly AnnouncementService _announcementService;
        private readonly CommentService _commentService;
        public AnnouncementController(ApplicationDbContext context, ILogger<AnnouncementController> logger, AnnouncementService announcementService,
            CommentService commentService)
            : base(context, logger)
        {
            _announcementService = announcementService;
            _commentService = commentService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int? page)
        {
            try
            {
                var pageNumber = page ?? 1;
                var pageSize = 10;

                var announcements = await _announcementService.GetAllAnnouncementsAsync();
                var pagedAnnouncements = announcements.ToPagedList(pageNumber, pageSize);
                
                return View(pagedAnnouncements);
            }

            catch (ApplicationException ex)
            {
                TempData["Error"]  = ex.Message;
            }

            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult>Create(AnnouncementViewModel m)
        {
            var memberId = User.FindFirstValue(ClaimTypes.NameIdentifier) ?? "Not found.";

            if (ModelState.IsValid)
            {
                try
                {
                    var announcement = await _announcementService.CreateNewAnnouncementAsync(m, memberId);
                    return RedirectToAction("Index");
                }

                catch (ApplicationException ex)
                {
                    TempData["Error"] = ex.Message;
                    _logger.LogError(ex, "There was an error creating the announcement.");
                }
            }

            return View(m);
        }

        [HttpGet]
        public async Task<IActionResult>GetAnnouncementCommentsById(int id)
        {
            var comments = await _commentService.GetCommentsByAnnouncementId(id);

            return PartialView("_AnnouncementCommentsPartial", comments);
        }
    }
}

XraySocialClub/Areas/Administration/Controllers/MemberController.cs
using Microsoft.AspNetCore.Mvc;
using X.PagedList.Extensions;
using XraySocialClub.Areas.Administration.Models.Member;
using XraySocialClub.Data;
using XraySocialClub.Data.Core;
using XraySocialClub.Services;

namespace XraySocialClub.Areas.Administration.Controllers
{
    public class MemberController : AdministrationController
    {
        private readonly OrganisationService _organisationService;
        public MemberController(ApplicationDbContext context, ILogger<MemberController> logger, OrganisationService organisationService)
            : base(context, logger)
        {
            _organisationService = organisationService;
        }
        
        [HttpGet]
        public async Task<IActionResult> Index(bool? isLotto, int? page)
        {
            int pageNumber = page ?? 1;
            int pageSize = 5;
            
            switch (isLotto)
            {
                case true:
                    var lottoMembers = await _organisationService.GetLottoMembersAsync();
                    var pagedLottoMembers = lottoMembers.ToPagedList(pageNumber, pageSize);
                    return View(pagedLottoMembers);
                case false:
                    var socialMembers = await _organisationService.GetSocialMembersAsync();
                    var pagedSocialMembers = socialMembers.ToPagedList(pageNumber, pageSize);
                    return View(pagedSocialMembers);
                default:
                    var members = await _organisationService.GetAllMembersAsync();
                    var pagedMembers = members.ToPagedList(pageNumber, pageSize);
                    return View(pagedMembers);
            }
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel m)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    await _organisationService.RegisterMemberAsync(1, m.FirstName!, m.LastName!, m.Email!, m.Role);
                    return RedirectToAction("Index");
                }

                catch (ApplicationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    _logger.LogError(ex, "There was an error registering the member.");
                }
            }

            return View(m);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            try
            {
                var member = await _organisationService.GetMemberByIdAsync(id);

                var m = new EditViewModel()
                {
                    Id = member.Id,
                    FirstName = member.FirstName,
                    LastName = member.LastName,
                    Email = member.Email ?? "Not available",
                    Roles = await _organisationService.GetUserRolesAsync(member)
                };

                return View(m);
            }

            catch(ApplicationException ex)
            {
                TempData["Error"] = ex.Message;
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditViewModel m)
        {
            var member = new Member();

            try
            {
                member = await _organisationService.GetMemberByIdAsync(m.Id!);
                
                if (m.RoleName != null && m.RemoveRole == true)
                {
                    switch(m.RoleName)
                    {
                        case "Social":
                            member.UserRoles.Remove(Role.Social);
                            break;
                        case "Lotto":
                            member.UserRoles.Remove(Role.Lotto);
                            break;
                        case "Pending":
                            member.UserRoles.Remove(Role.Pending);
                            break;
                        case "Administrator":
                            member.UserRoles.Remove(Role.Administrator);
                            break;
                    }
                    
                    await _organisationService.RemoveMemberFromRoleAsync(member, m.RoleName);
                }
            }

            catch(ApplicationException ex)
            {
                TempData["Error"] = ex.Message;
                _logger.LogError(ex, "There was an error modifying the user role details.");
            }

            if (ModelState.IsValid)
            {
                member.FirstName = m.FirstName!;
                member.LastName = m.LastName!;
                member.Email = m.Email;
                
                try
                {
                    await _organisationService.UpdateMemberDetailsAsync(member);
                    await _organisationService.AddMemberToRoleAsync(member, m.Role!.Value);  
                }

                catch (ApplicationException ex)
                {
                    TempData["Error"] = ex.Message;
                    _logger.LogError(ex, "There was an error updating the user details.");
                }
            }

            TempData["Success"] = "Member Details Updated Sucessfully.";
            
            return RedirectToAction("Edit");
        }
    }
}

XraySocialClub/Areas/Administration/Controllers/PurchaseController.cs
using Microsoft.AspNetCore.Mvc;
using X.PagedList.Extensions;
using XraySocialClub.Areas.Administration.Models.Purchase;
using XraySocialClub.Data.Core;
using XraySocialClub.Services;

namespace XraySocialClub.Areas.Administration.Controllers
{
    public class PurchaseController : AdministrationController
    {
        private readonly PurchaseService _purchaseService;
        public PurchaseController(ApplicationDbContext context, ILogger<PurchaseController> logger,
            PurchaseService purchaseService) : base(context, logger)
        {
            _purchaseService = purchaseService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int? page)
        {
            try
            {
                var pageNumber = page ?? 1;
                var pageSize = 10;

                var purchases = await _purchaseService.GetAllPurchaseRecordsAsync();
                var pagedPurchases = purchases.ToPagedList(pageNumber, pageSize);
                
                return View(pagedPurchases);
            }
            
            catch (ApplicationException ex)
            {
                TempData["Error"] = ex.Message;
            }

            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            var m = new PurchaseViewModel()
            {
                DatePurchased = DateTime.UtcNow,
            };

            return View(m);
        }

        [HttpPost]
        public async Task<IActionResult> Create(PurchaseViewModel m)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var purchaseRecord = await _purchaseService.CreatePurchaseRecordAsync(m);
                }

                catch (ApplicationException ex)
                {
                    TempData["Error"] = ex.Message;
                    _logger.LogError(ex, "There was an error creating the purchase record.");
                    return View();
                }
            }
            return RedirectToAction("Index");
        }
    }
}

XraySocialClub/Areas/Administration/Controllers/TicketController.cs
using Microsoft.AspNetCore.Mvc;
using X.PagedList.Extensions;
using XraySocialClub.Areas.Administration.Models.Ticket;
using XraySocialClub.Data.Core;
using XraySocialClub.Services;

namespace XraySocialClub.Areas.Administration.Controllers
{
    public class TicketController : AdministrationController
    {
        private readonly TicketService _ticketService;
        private readonly OrganisationService _organisationService;
        public TicketController(ApplicationDbContext context, ILogger<TicketController> logger, OrganisationService organisationService, TicketService ticketService)
            : base(context, logger)
        {
            _organisationService = organisationService;
            _ticketService = ticketService;
        }

        [HttpGet]
        public async Task <IActionResult> Index(bool? isActive, int? page)
        {
            try
            {
                var pageNumber = page ?? 1;
                var pageSize = 10;

                ViewBag.Total = await _ticketService.TotalAmountSpentOnTicketsAsync();

                switch(isActive)
                {
                    case true:
                        var activeTickets = await _ticketService.GetAllActiveTicketsAsync();
                        var pagedActiveTickets = activeTickets.ToPagedList(pageNumber, pageSize);
                        return View(pagedActiveTickets);
                    case false:
                        var archivedTickets = await _ticketService.GetArchivedTicketsAsync();
                        var pagedArchivedTickets = archivedTickets.ToPagedList(pageNumber, pageSize);
                        return View(pagedArchivedTickets);
                    default:
                        var tickets = await _ticketService.GetAllTicketsAsync();
                        var pagedTickets = tickets.ToPagedList(pageNumber, pageSize);
                        return View(pagedTickets);
                }
            }
            
            catch (ApplicationException ex)
            {
                TempData["Error"] = ex.Message;
            }

            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            var m = new TicketViewModel()
            {
                DrawDate = DateTime.UtcNow,
            };

            return View(m);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TicketViewModel m)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    var ticket = await _ticketService.CreateNewTicketAsync(m);
                }

                catch(ApplicationException ex)
                {
                    TempData["Error"] = ex.Message;
                    return View(m);
                }
            }

            TempData["Success"] = "Ticket created successfully";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> ArchiveTicket(int id)
        {
            try
            {
                var ticket = await _ticketService.ArchiveTicketAsync(id);

                if (ticket == true)
                {
                    TempData["Success"] = "Ticket archived successfully.";
                }

                else
                {
                    TempData["Error"] = "Ticket could not be archived at this time.";
                }
            }

            catch (ApplicationException ex)
            {
                // Add to view
                TempData["Error"] = ex.Message;
            }

            return Json(new { redirectToUrl = Url.Action("Index")});
        }

        [HttpPost]
        public async Task<IActionResult> ActivateTicket(int id)
        {
            try
            {
                var ticket = await _ticketService.ActivateTicketAsync(id);

                if (ticket == true)
                {
                    TempData["Success"] = "Ticket activated successfully.";
                }

                else
                {
                    TempData["Error"] = "Ticket could not be activated at this time.";
                }
            }

            catch (ApplicationException ex)
            {
                // Add to view
                TempData["Error"] = ex.Message;
                _logger.LogError(ex, "There was an error activating the ticket.");
            }

            return Json(new { redirectToUrl = Url.Action("Index")});
        }

        [HttpGet]
        public async Task<IActionResult> CreateRecord()
        {
            var m = new TicketRecordViewModel()
            {
                Members = await _organisationService.GetLottoMembersAsync(),
            };

            return View(m);
        }

        [HttpPost]
        public async Task<IActionResult> CreateRecord(TicketRecordViewModel m)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    await _ticketService.CreateTicketRecordForMemberAsync(m);
                }

                catch (ApplicationException ex)
                {
                    TempData["Error"] = ex.Message;
                    _logger.LogError(ex, "There was an error creating the ticket record.");
                    return View(m);
                }
            }
            TempData["Success"] = "Ticket record created successfully for member(s).";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> TicketRecord(string id)
        {
            try
            {
                var ticketRecords = await _ticketService.GetTicketRecordsForMemberAsync(id);
                return View(ticketRecords);
            }
            
            catch(ApplicationException ex)
            {
                TempData["Error"] = ex.Message;
            }
            
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ViewTicketMembers(int id)
        {
            try
            {
                var members = await _ticketService.GetMembersForTicketAsync(id);
                return PartialView("_TicketMembersPartial", members);
            }
            
            catch (ApplicationException ex)
            {
                TempData["Error"] = ex.Message;
            }

            return View();
        }
    }
}

XraySocialClub/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using XraySocialClub.Models;
using XraySocialClub.Services;

namespace XraySocialClub.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly AnnouncementService _announcementService;

        public HomeController(ILogger<HomeController> logger, AnnouncementService announcementService)
        {
            _logger = logger;
            _announcementService = announcementService;
        }

        public async Task<IActionResult> Index()
        {
            var announcements = await _announcementService.GetLastThreeAnnouncementsAsync();
            return View(announcements);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

XraySocialClub/Views/Home/Index.cshtml
@model IEnumerable<Announcement>

<div class="bg-dark text-secondary px-4 py-5 text-center rounded mb-4">
    <div class="py-5">
        <h1 class="display-5 fw-bold text-white">Welcome to XraySocialClub!</h1>
        <div class="col-lg-6 mx-auto">
            @if (User.Identity != null && !User.Identity.IsAuthenticated)
            {
                <p class="lead mb-4">Log in with an existing account or sign up with us today!</p>
                <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                    <a class="btn btn-primary btn-lg px-4 gap-3" asp-area="Identity" asp-page="/Account/Register">Sign
                        Up</a>
                    <a class="btn btn-outline-secondary btn-lg px-4" asp-area="Identity" asp-page="/Account/Login">Log
                        In</a>
                </div>
            }
            else
            {
                <p class="lead mt-4">Hi @(User.Identity?.Name ?? "User")! What would you like to do today? &#128512;</p>
            }
        </div>
    </div>
</div>

<div class="mb-3">
    <h4 class="text-center mb-3">Latest Announcements From Our Team! <span class="badge text-bg-secondary">New</span></h4>
    @foreach (var m in Model)
    {
        <div class="card text-center shadow-sm mb-5">
            @*TODO: Image placeholder: need to scale image to an ok size *@

            @if (m.ImageUrl == "No image specified.")
            {
                @*TODO: Set an actual placeholder image here*@
                @* <img src="https://via.placeholder.com/150" class="card-img-top" alt="..."> *@
            }
            else
            {
                <img src="@m.ImageUrl" class="card-img-top img-fluid" alt="..." style="object-fit: cover; width: 100%; height: 400px;">
            }
            <div class="card-body">
                <h5 class="card-title">@m.Title</h5>
                <p class="card-text">@m.Description</p>
            </div>
            <div class="card-footer text-body-secondary small text-muted">
                @Extensions.AsTimeAgo(m.Date) by @m.Member.FirstName @m.Member.LastName
            </div>
        </div>
    }
</div>

@if (User.Identity != null && User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
{
    <div class="album py-5 border border-secondary-subtle shadow-lg rounded">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <div class="col">
                    <div class="card shadow-sm">
                        <img src="~/images/information.jpg" alt="Purchase Record" />
                        <div class="card-body">
                            <p class="card-text">Add a new announcement or view previous announcements.</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-sm btn-outline-secondary" asp-area="Administration"
                                        asp-controller="Announcement" asp-action="Index">View</a>
                                    <a class="btn btn-sm btn-outline-secondary" asp-area="Administration"
                                        asp-controller="Announcement" asp-action="Create">Create</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-sm">
                        <img src="~/images/register.jpg" alt="Register Member Log" />
                        <div class="card-body">
                            <p class="card-text">Register new members, update payment records, and assign roles.</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-sm btn-outline-secondary" asp-area="Administration"
                                        asp-controller="Member" asp-action="Index">Manage</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-sm">
                        <img src="~/images/lottoticket.jpg" alt="Lotto Ticket" />
                        <div class="card-body">
                            <p class="card-text">View previous purchased ticket records or add a new ticket record.</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-sm btn-outline-secondary" asp-area="Administration"
                                        asp-controller="Ticket" asp-action="Index">View</a>
                                    <a class="btn btn-sm btn-outline-secondary" asp-area="Administration"
                                        asp-controller="Ticket" asp-action="Create">Create</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col mx-auto">
                    <div class="card shadow-sm">
                        <img src="~/images/purchase.jpg" alt="Purchase Record" />
                        <div class="card-body">
                            <p class="card-text">View previous purchases or add a new purchase record.</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-sm btn-outline-secondary" asp-area="Administration"
                                        asp-controller="Purchase" asp-action="Index">View</a>
                                    <a class="btn btn-sm btn-outline-secondary" asp-area="Administration"
                                        asp-controller="Purchase" asp-action="Create">Create</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}