XraySocialClub/Areas/Administration/Models/EditViewModel.cs
namespace XraySocialClub.Areas.Administration.Models;

public class EditViewModel : RegisterViewModel
{ 
    public string Id { get; set; } = default!;
    public IEnumerable<string> Roles { get; set; } = new List<string>();
    public string? RoleName { get; set; } = default!;
    public bool? RemoveRole { get; set; }
}

XraySocialClub/Areas/Administration/Controllers/MemberController.cs
using Microsoft.AspNetCore.Mvc;
using X.PagedList.Extensions;
using XraySocialClub.Areas.Administration.Models.Member;
using XraySocialClub.Data;
using XraySocialClub.Data.Core;
using XraySocialClub.Services;

namespace XraySocialClub.Areas.Administration.Controllers
{
    public class MemberController : AdministrationController
    {
        private readonly OrganisationService _organisationService;
        public MemberController(ApplicationDbContext context, ILogger<MemberController> logger, OrganisationService organisationService)
            : base(context, logger)
        {
            _organisationService = organisationService;
        }
        
        [HttpGet]
        public async Task<IActionResult> Index(bool? isLotto, int? page)
        {
            int pageNumber = page ?? 1;
            int pageSize = 5;
            
            switch (isLotto)
            {
                case true:
                    var lottoMembers = await _organisationService.GetLottoMembersAsync();
                    var pagedLottoMembers = lottoMembers.ToPagedList(pageNumber, pageSize);
                    return View(pagedLottoMembers);
                case false:
                    var socialMembers = await _organisationService.GetSocialMembersAsync();
                    var pagedSocialMembers = socialMembers.ToPagedList(pageNumber, pageSize);
                    return View(pagedSocialMembers);
                default:
                    var members = await _organisationService.GetAllMembersAsync();
                    var pagedMembers = members.ToPagedList(pageNumber, pageSize);
                    return View(pagedMembers);
            }
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel m)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    await _organisationService.RegisterMemberAsync(1, m.FirstName!, m.LastName!, m.Email!, m.Role);
                    return RedirectToAction("Index");
                }

                catch (ApplicationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    _logger.LogError(ex, "There was an error registering the member.");
                }
            }

            return View(m);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            try
            {
                var member = await _organisationService.GetMemberByIdAsync(id);

                var m = new EditViewModel()
                {
                    Id = member.Id,
                    FirstName = member.FirstName,
                    LastName = member.LastName,
                    Email = member.Email ?? "Not available",
                    Roles = await _organisationService.GetUserRolesAsync(member)
                };

                return View(m);
            }

            catch(ApplicationException ex)
            {
                TempData["Error"] = ex.Message;
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditViewModel m)
        {
            var member = new Member();

            try
            {
                member = await _organisationService.GetMemberByIdAsync(m.Id!);
                
                if (m.RoleName != null && m.RemoveRole == true)
                {
                    switch(m.RoleName)
                    {
                        case "Social":
                            member.UserRoles.Remove(Role.Social);
                            break;
                        case "Lotto":
                            member.UserRoles.Remove(Role.Lotto);
                            break;
                        case "Pending":
                            member.UserRoles.Remove(Role.Pending);
                            break;
                        case "Administrator":
                            member.UserRoles.Remove(Role.Administrator);
                            break;
                    }
                    
                    await _organisationService.RemoveMemberFromRoleAsync(member, m.RoleName);
                }
            }

            catch(ApplicationException ex)
            {
                TempData["Error"] = ex.Message;
                _logger.LogError(ex, "There was an error modifying the user role details.");
            }

            if (ModelState.IsValid)
            {
                member.FirstName = m.FirstName!;
                member.LastName = m.LastName!;
                member.Email = m.Email;
                
                try
                {
                    await _organisationService.UpdateMemberDetailsAsync(member);
                    await _organisationService.AddMemberToRoleAsync(member, m.Role!.Value);  
                }

                catch (ApplicationException ex)
                {
                    TempData["Error"] = ex.Message;
                    _logger.LogError(ex, "There was an error updating the user details.");
                }
            }

            TempData["Success"] = "Member Details Updated Sucessfully.";
            
            return RedirectToAction("Edit");
        }
    }
}

XraySocialClub/Areas/Administration/Controllers/PaymentController.cs
using Microsoft.AspNetCore.Mvc;
using X.PagedList.Extensions;
using XraySocialClub.Areas.Administration.Models.Payment;
using XraySocialClub.Data.Core;
using XraySocialClub.Services;

namespace XraySocialClub.Areas.Administration.Controllers
{
    public class PaymentController : AdministrationController
    {
        public readonly PaymentService _paymentService;
        public PaymentController(ApplicationDbContext context, ILogger<PaymentController> logger, PaymentService paymentService)
            : base(context, logger)
        {
            _paymentService = paymentService;
        }

        public async Task<IActionResult> Index(string id, int? page)
        {
            try
            {
                var pageNumber = page ?? 1;
                var pageSize = 10;

                var paymentRecord = await _paymentService.GetPaymentRecordForMemberAsync(id);
                var pagedPaymentReconds = paymentRecord.ToPagedList(pageNumber, pageSize);

                ViewBag.PaymentTotal = await _paymentService.GetSumOfMembersPaymentsAsync(id);
                return View(pagedPaymentReconds);
            }

            catch (ApplicationException ex)
            {
                TempData["Error"] = ex.Message;
            }
            return View();
        }

        [HttpGet]
        public IActionResult Create(string id)
        {
            var m = new PaymentViewModel()
            {
                MemberId = id,
                DatePaid = DateTime.UtcNow,
            };

            return View(m);
        }

        [HttpPost]
        public async Task<IActionResult> Create(string id, PaymentViewModel m)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var paymentRecord = await _paymentService.CreatePaymentRecordForMemberAsync(id, m);
                }

                catch (ApplicationException ex)
                {
                    TempData["Error"] = ex.Message;
                    _logger.LogError(ex, "There was an error trying to create a payment record.");
                    return View(m);
                }
            }
            
            TempData["Success"] = "Payment Record created for member.";
            return RedirectToAction("Index", new {id});
        }
    }
}

XraySocialClub/Areas/Administration/Controllers/TicketController.cs
using Microsoft.AspNetCore.Mvc;
using X.PagedList.Extensions;
using XraySocialClub.Areas.Administration.Models.Ticket;
using XraySocialClub.Data.Core;
using XraySocialClub.Services;

namespace XraySocialClub.Areas.Administration.Controllers
{
    public class TicketController : AdministrationController
    {
        private readonly TicketService _ticketService;
        private readonly OrganisationService _organisationService;
        public TicketController(ApplicationDbContext context, ILogger<TicketController> logger, OrganisationService organisationService, TicketService ticketService)
            : base(context, logger)
        {
            _organisationService = organisationService;
            _ticketService = ticketService;
        }

        [HttpGet]
        public async Task <IActionResult> Index(bool? isActive, int? page)
        {
            try
            {
                var pageNumber = page ?? 1;
                var pageSize = 10;

                ViewBag.Total = await _ticketService.TotalAmountSpentOnTicketsAsync();

                switch(isActive)
                {
                    case true:
                        var activeTickets = await _ticketService.GetAllActiveTicketsAsync();
                        var pagedActiveTickets = activeTickets.ToPagedList(pageNumber, pageSize);
                        return View(pagedActiveTickets);
                    case false:
                        var archivedTickets = await _ticketService.GetArchivedTicketsAsync();
                        var pagedArchivedTickets = archivedTickets.ToPagedList(pageNumber, pageSize);
                        return View(pagedArchivedTickets);
                    default:
                        var tickets = await _ticketService.GetAllTicketsAsync();
                        var pagedTickets = tickets.ToPagedList(pageNumber, pageSize);
                        return View(pagedTickets);
                }
            }
            
            catch (ApplicationException ex)
            {
                TempData["Error"] = ex.Message;
            }

            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            var m = new TicketViewModel()
            {
                DrawDate = DateTime.UtcNow,
            };

            return View(m);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TicketViewModel m)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    var ticket = await _ticketService.CreateNewTicketAsync(m);
                }

                catch(ApplicationException ex)
                {
                    TempData["Error"] = ex.Message;
                    return View(m);
                }
            }

            TempData["Success"] = "Ticket created successfully";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> ArchiveTicket(int id)
        {
            try
            {
                var ticket = await _ticketService.ArchiveTicketAsync(id);

                if (ticket == true)
                {
                    TempData["Success"] = "Ticket archived successfully.";
                }

                else
                {
                    TempData["Error"] = "Ticket could not be archived at this time.";
                }
            }

            catch (ApplicationException ex)
            {
                // Add to view
                TempData["Error"] = ex.Message;
            }

            return Json(new { redirectToUrl = Url.Action("Index")});
        }

        [HttpPost]
        public async Task<IActionResult> ActivateTicket(int id)
        {
            try
            {
                var ticket = await _ticketService.ActivateTicketAsync(id);

                if (ticket == true)
                {
                    TempData["Success"] = "Ticket activated successfully.";
                }

                else
                {
                    TempData["Error"] = "Ticket could not be activated at this time.";
                }
            }

            catch (ApplicationException ex)
            {
                // Add to view
                TempData["Error"] = ex.Message;
                _logger.LogError(ex, "There was an error activating the ticket.");
            }

            return Json(new { redirectToUrl = Url.Action("Index")});
        }

        [HttpGet]
        public async Task<IActionResult> CreateRecord()
        {
            var m = new TicketRecordViewModel()
            {
                Members = await _organisationService.GetLottoMembersAsync(),
            };

            return View(m);
        }

        [HttpPost]
        public async Task<IActionResult> CreateRecord(TicketRecordViewModel m)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    await _ticketService.CreateTicketRecordForMemberAsync(m);
                }

                catch (ApplicationException ex)
                {
                    TempData["Error"] = ex.Message;
                    _logger.LogError(ex, "There was an error creating the ticket record.");
                    return View(m);
                }
            }
            TempData["Success"] = "Ticket record created successfully for member(s).";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> TicketRecord(string id)
        {
            try
            {
                var ticketRecords = await _ticketService.GetTicketRecordsForMemberAsync(id);
                return View(ticketRecords);
            }
            
            catch(ApplicationException ex)
            {
                TempData["Error"] = ex.Message;
            }
            
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ViewTicketMembers(int id)
        {
            try
            {
                var members = await _ticketService.GetMembersForTicketAsync(id);
                return PartialView("_TicketMembersPartial", members);
            }
            
            catch (ApplicationException ex)
            {
                TempData["Error"] = ex.Message;
            }

            return View();
        }
    }
}

XraySocialClub/Areas/Identity/Pages/Account/Register.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using XraySocialClub.Data;
using XraySocialClub.Data.Core;
using XraySocialClub.Services;

namespace XraySocialClub.Areas.Identity.Pages.Account
{
    public class RegisterModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly SignInManager<OrganisationUser> _signInManager;
        private readonly OrganisationService _organisationService;

        public RegisterModel(SignInManager<OrganisationUser> signInManager, ApplicationDbContext context, OrganisationService organisationService)
        {
            _signInManager = signInManager;
            _context = context;
            _organisationService = organisationService;
        }

        [BindProperty]
        public InputModel Input { get; set; }
        public class InputModel
        {
            [Required]
            public int OrganisationId { get; set; } = 1;
            [Required]
            [DisplayName("First Name")]
            public string FirstName { get; set;}
            [Required]
            [DisplayName("Last Name")]
            public string LastName { get; set; }
            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }
            public Role Role { get; set; } = Role.Pending;
            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }
            [DataType(DataType.Password)]
            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }
        }
        
        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var member = await _organisationService.RegisterMemberAsync(Input.OrganisationId, Input.FirstName, Input.LastName, Input.Email, Input.Role, Input.Password);

                    await _signInManager.SignInAsync(await _context.Users.FirstAsync(user => user.Id == member.Id), false);
                    return LocalRedirect("/");
                }
                catch (InvalidOperationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return Page();
        }

    }
}

XraySocialClub/Areas/Administration/Views/Member/Edit.cshtml
@model EditViewModel

<div class="my-5">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb p-3 bg-body-tertiary rounded-3">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="@Url.ActionLink("Index","Member")">Members</a></li>
            <li class="breadcrumb-item active" aria-current="page">Edit Member</li>
        </ol>
    </nav>
</div>

@{
    ViewData["Title"] = "Edit Member";
}
<div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold">@ViewData["Title"]</h1>
</div>

@if (TempData["Success"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Success"]
    </div>
}


<div class="card p-4 shadow-lg">
    <form asp-action="Edit" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        @foreach (var role in Model.Roles)
        {
            <span class="badge text-bg-dark mb-3">@role</span>
        }

        <div class="form-floating mb-3">
            <input asp-for="Id" disabled class="form-control" id="floatingInput">
            <label asp-for="Id">Id</label>
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>

        <div class="form-floating mb-3">
            <input asp-for="FirstName" class="form-control" id="floatingInput">
            <label asp-for="FirstName">First Name</label>
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>

        <div class="form-floating mb-3">
            <input asp-for="LastName" class="form-control" id="floatingInput">
            <label asp-for="LastName">Last Name</label>
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>

        <div class="form-floating mb-3">
            <input asp-for="Email" type="email" class="form-control" id="floatingInput">
            <label asp-for="Email">Email Address</label>
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>

        <div class="form-floating mb-3">
            <select class="form-select" id="floatingSelect" aria-label="Role Select" asp-for="Role"
                    asp-items="Html.GetEnumSelectList<Role>()">
                <option selected>Select a role</option>
            </select>
            <label for="floatingSelect">Role</label>
        </div>

        <button type="submit" class="btn btn-primary w-100 mb-3">Update Member Details</button>
    </form>

    <form asp-action="Edit" method="post">
        @foreach (var role in Model.Roles)
        {
            <input type="hidden" asp-for="RemoveRole" value="true" />
            <input type="hidden" asp-for="RoleName" value="@role" />
            <div>
                <button type="submit" class="btn btn-outline-secondary w-100 mb-3">Remove @role Role</button>
            </div>
        }
    </form>
</div>

XraySocialClub/Areas/Administration/Views/Member/Index.cshtml
@model IPagedList<Member>

<div class="my-5">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb p-3 bg-body-tertiary rounded-3">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Members</li>
        </ol>
    </nav>
</div>

@{
    ViewData["Title"] = "Members";
}

<div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold">@ViewData["Title"]</h1>
</div>

<a class="btn btn-primary mb-3" asp-action="Register">Register Member</a>

<div class="card p-4 shadow-lg mb-3">
    <div class="class-body">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Email Address</th>
                    <th scope="col">Administration</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var m in Model)
                {
                    <tr>
                        <th scope="row">@m.Id</th>
                        <td>@m.FirstName</td>
                        <td>@m.LastName</td>
                        <td>@m.Email</td>
                        <td>
                            <a href="@Url.Action("Edit", "Member", new { id = m.Id })"
                                class="link-underline-primary">Update</a> | <a
                                href="@Url.Action("Index", "Payment", new { id = m.Id })" class="link-underline-primary"
                                role="button">Payment</a> |
                            @if (m.UserRoles.Contains(Role.Lotto))
                            {
                                <a href="@Url.Action("TicketRecord", "Ticket", new { id = m.Id })"
                                    class="link-underline-primary">Records</a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }),
        new PagedListRenderOptions
        {
            LiElementClasses = new string[] { "page-item" },
            PageClasses = new string[] { "page-link" }
        })

    </div>
</div>

<a class="btn btn-primary float-end" asp-action="Index" asp-controller="Member" asp-route-isLotto="false"
    role="button">Social Members</a>
<a class="btn btn-primary float-end me-1" asp-action="Index" asp-controller="Member" asp-route-isLotto="true"
    role="button">Lotto Members</a>
<a class="btn btn-primary float-end mb-3 me-1" asp-action="Index" asp-controller="Member" role="button">All Members</a>

XraySocialClub/Areas/Administration/Views/Member/Register.cshtml
@model RegisterViewModel

@{
    ViewData["Title"] = "Register Member";
}
<div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold">@ViewData["Title"]</h1>
</div>

<form asp-action="Register" method="post" class="card p-4 shadow-lg">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="form-floating mb-3">
        <input asp-for="FirstName" class="form-control" id="floatingInput">
        <label asp-for="FirstName">First Name</label>
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>

    <div class="form-floating mb-3">
        <input asp-for="LastName" class="form-control" id="floatingInput">
        <label asp-for="LastName">Last Name</label>
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>

    <div class="form-floating mb-3">
        <input asp-for="Email" type="email" class="form-control" id="floatingInput">
        <label asp-for="Email">Email Address</label>
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div class="form-floating mb-3">
        <select class="form-select" id="floatingSelect" aria-label="Role Select" asp-for="Role"
                asp-items="Html.GetEnumSelectList<Role>()">
        </select>
        <label for="floatingSelect">Role</label>
    </div>
    <button type="submit" class="btn btn-primary">Register</button>
</form>